import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '@/lib/seo';
import { LegalTemplate } from '@/components/templates/LegalTemplate';

export const metadata: Metadata = buildMetadata({
  path: '/terms',
  title: 'Terms of Service — Nor AI Technologies Private Limited',
  description:
    'Review the Terms of Service governing the use of NorAI micro-tools, API endpoints, and enterprise automation services.',
});

const TERMS_SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    paragraphs: [
      'By accessing or using the NorAI Technologies website, web dashboards, REST API endpoints, or micro-SaaS utilities (collectively, the "Services"), you agree to be bound by these Terms of Service.',
      'If you are entering into this agreement on behalf of a business entity, you represent that you have the authority to bind such entity to these Terms.',
    ],
  },
  {
    id: 'license',
    title: '2. API License & Permitted Use',
    paragraphs: [
      'NorAi Technologies grants you a non-exclusive, non-transferable, revocable license to access and use our AI utilities in accordance with your subscription plan.',
      'You agree not to reverse engineer, decompile, or attempt to extract source model weights from NorAI neural inference pipelines.',
    ],
  },
  {
    id: 'privacy',
    title: '3. Data Privacy & Zero Persistent Logging',
    paragraphs: [
      'We enforce a strict Zero Persistent Logging policy for standard API inferencing payloads. Input documents, resumes, or lecture recordings are processed in memory and immediately discarded upon response completion.',
      'Customer data is never sold, shared, or utilized to train public foundation models.',
    ],
  },
  {
    id: 'ip',
    title: '4. Intellectual Property Rights',
    paragraphs: [
      'All output text summaries, candidate scores, flashcards, and digested briefs generated by our Services are the exclusive property of the user.',
      'NorAi retains all ownership rights to the underlying software architecture, micro-tools, brand assets, and proprietary orchestration algorithms.',
    ],
  },
  {
    id: 'liability',
    title: '5. Limitation of Liability',
    paragraphs: [
      'NorAi Services are provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, NorAI Technologies shall not be liable for any indirect, incidental, or consequential damages.',
      'Our maximum aggregate liability for any claims arising from the Services is limited to the amount paid by you in the 12 months preceding the claim.',
    ],
  },
  {
    id: 'law',
    title: '6. Governing Law & Jurisdiction',
    paragraphs: [
      'These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.',
      'Any legal action or proceeding arising under these Terms shall be brought exclusively in the courts located in Uttar Pradesh, India.',
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalTemplate
      eyebrow="Legal"
      title="Terms of Service"
      subtitle="Nor AI Technologies Private Limited · CIN: U62011UP2026PTC252801 · PAN: AAMCN1061B · Umarganj, Zamania, Ghazipur, Uttar Pradesh, India — 232329"
      lastUpdated="January 1, 2026"
      sections={TERMS_SECTIONS}
      footer={
        <div className="space-y-3 rounded-xl border border-line-subtle bg-canvas-paper p-6 shadow-sm">
          <h2 className="font-display text-xl text-ink-primary">Questions about our terms?</h2>
          <p className="text-sm leading-[1.75] text-ink-body">
            For custom enterprise agreement terms or DPA requests, email{' '}
            <a
              href="mailto:noraitechnologies@gmail.com"
              className="font-semibold text-terra-600 underline underline-offset-4 transition-colors duration-200 hover:text-terra-700"
            >
              noraitechnologies@gmail.com
            </a>{' '}
            or reach us through the{' '}
            <Link
              href="/contact"
              className="font-semibold text-terra-600 underline underline-offset-4 transition-colors duration-200 hover:text-terra-700"
            >
              contact page
            </Link>
            .
          </p>
        </div>
      }
    />
  );
}
