export interface LegalPolicySection {
  heading: string;
  paragraphs: string[];
}

export interface LegalPolicyData {
  slug: string;
  title: string;
  lastUpdated: string;
  description: string;
  sections: LegalPolicySection[];
}

export const CONTACT_EMAIL = 'noraitechnologies@gmail.com';

/**
 * The single source of truth for legal copy.
 *
 * These documents describe what the business actually does. NorAI runs four
 * BYOK browser tools, custom engineering services, and a civic AI-literacy
 * programme. There is no account system, no billing, no credit system, no
 * public API, no SDK, and no database, so none of those are described here.
 * The only server-side data is anonymous rate-limit bookkeeping, and the
 * browser tools call Google's Gemini API directly with the visitor's own key.
 */
export const LEGAL_POLICIES: Record<string, LegalPolicyData> = {
  'privacy-policy': {
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    lastUpdated: 'January 15, 2026',
    description:
      'How NorAI Technologies handles data on norai.tech. Tools are browser-based and bring-your-own-key, so we never receive your input.',
    sections: [
      {
        heading: '1. Who We Are',
        paragraphs: [
          'NorAI Technologies Private Limited ("NorAI", "we", "us") is an AI engineering practice with registered offices at Umarganj, Zamania, Ghazipur, Uttar Pradesh, India. This policy describes what happens to data when you use norai.tech.',
        ],
      },
      {
        heading: '2. What We Receive',
        paragraphs: [
          'When you use the four browser tools on this site, your text, documents, or chat logs are sent by your own browser to Google\'s Gemini API. Your API key travels in a request header directly to Google. NorAI servers see the request only far enough to validate the payload, rate-limit it, and pass it onward; we do not store your input or your output.',
          'We do not ask you to create an account, and we do not operate a user database, billing system, or credit ledger.',
          'When you submit the contact form, we receive the name, email address, company, selected service, and message you type. That enquiry is delivered by email to the practice and is the only personal data we hold from you.',
        ],
      },
      {
        heading: '3. What We Keep on the Server',
        paragraphs: [
          'The only server-side record associated with a request is anonymous rate-limit bookkeeping: a coarse client address and a count of recent requests, held in memory only and discarded. It is not linked to an account, because there are no accounts.',
        ],
      },
      {
        heading: '4. Where Data Is Processed',
        paragraphs: [
          'This website is hosted on managed infrastructure that provides transport encryption. Model inference happens at Google, under Google\'s own terms, using the key you supply. If you do not wish to send content to Google, do not run a tool with that content.',
        ],
      },
      {
        heading: '5. Your Choices',
        paragraphs: [
          'Because we do not hold an account or a database, there is generally nothing for us to export or delete. If you have sent us an enquiry and want it removed, or you have any privacy question, email us and a person will handle it.',
        ],
      },
    ],
  },
  'terms-of-service': {
    slug: 'terms-of-service',
    title: 'Terms of Service',
    lastUpdated: 'January 15, 2026',
    description:
      'Terms governing use of the NorAI website, its four BYOK browser tools, and NorAI engineering services. Governed by the laws of India.',
    sections: [
      {
        heading: '1. Agreement',
        paragraphs: [
          'By using norai.tech or engaging NorAI Technologies Private Limited ("NorAI", "we", "us") you agree to these terms. If you do not agree, do not use the site.',
        ],
      },
      {
        heading: '2. The Browser Tools',
        paragraphs: [
          'NorAI publishes four tools that run in your browser: a resume shortlister, a course note-taker, a community chat digest, and a regional gazette reader. They are bring-your-own-key. You supply a Google Gemini API key, you bear any charges Google applies to that key, and the request is made by your browser to Google.',
          'We provide no public REST API, no SDK, and no hosted inference endpoint. These tools are offered as-is, with no uptime, latency, or accuracy commitment, and their output is generated by a language model and may be wrong.',
          'Do not submit confidential, personal, or regulated information to a tool unless your own policy permits it. You are responsible for what you paste in and for what you do with the result. In particular, a model-generated candidate score or eligibility summary is not a decision about a person.',
        ],
      },
      {
        heading: '3. Engineering Services',
        paragraphs: [
          'Custom engineering work is governed by a separate written agreement covering scope, deliverables, and fees. Where such an agreement conflicts with these terms, that agreement prevails.',
        ],
      },
      {
        heading: '4. Intellectual Property',
        paragraphs: [
          'The website, its design, its written content, and the source of the tools are owned by NorAI. Output produced by a tool belongs to you, subject to Google\'s terms governing model output. NorAI names, marks, and brand assets are not licensed by these terms.',
        ],
      },
      {
        heading: '5. No Warranty',
        paragraphs: [
          'The site and the tools are provided on an "as-is" and "as-available" basis, without warranties of any kind. We do not publish an availability figure, a response-time guarantee, or an accuracy benchmark, because we do not currently hold measurements we can evidence. To the extent permitted by law, NorAI is not liable for indirect or consequential loss arising from use of the site or the tools.',
        ],
      },
      {
        heading: '6. Governing Law',
        paragraphs: [
          'These terms are governed by the laws of India. Any dispute arising from them is subject to the exclusive jurisdiction of the courts at Ghazipur, Uttar Pradesh, India.',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Cookie Policy',
    lastUpdated: 'January 15, 2026',
    description:
      'What cookies and local storage norai.tech uses, why, and how to clear them. No advertising or cross-site tracking cookies are set.',
    sections: [
      {
        heading: '1. What We Store Locally',
        paragraphs: [
          'This site uses your browser\'s local storage rather than cookies for two things: your light or dark theme choice, and — only if you choose to use a tool — your Gemini API key and selected model, kept on your own device so the tool can call Google directly. Clearing your browser storage removes all of it.',
        ],
      },
      {
        heading: '2. Cookies We Do Not Set',
        paragraphs: [
          'We set no advertising, retargeting, or cross-site tracking cookies, and we do not sell or share data with advertising networks. We are not a registered data broker and do not build behavioural profiles.',
        ],
      },
      {
        heading: '3. Why Your Key Stays With You',
        paragraphs: [
          'Because the Gemini key is stored in your browser and sent from your browser to Google, it is never stored on a NorAI server. A key saved in local storage is only as safe as the device it is saved on — do not use a tool on a shared or public machine, and revoke the key in Google AI Studio if you think it has been exposed.',
        ],
      },
      {
        heading: '4. Removing It',
        paragraphs: [
          'You can clear this site\'s storage at any time through your browser settings, with no loss of function beyond resetting your theme and re-entering your key.',
        ],
      },
    ],
  },
};
