export const routes = {
  home: '/',
  products: '/products',
  productDetail: (slug: string) => `/products/${slug}`,
  services: '/services',
  about: '/about',
  mission: '/mission',
  team: '/team',
  careers: '/careers',
  contact: '/contact',
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
  docs: '/docs',
  privacy: '/privacy-policy',
  terms: '/terms-of-service',
  cookies: '/cookie-policy',
} as const;
